# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ObjectiveC-Lib/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'HJNetworkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'HJNetwork', :path => '../'
  pod 'HJNetwork/Default', :path => '../'
  pod 'HJNetwork/DNS', :path => '../'
  pod 'HJNetwork/Upload', :path => '../'
  pod 'HJNetwork/Download', :path => '../'
  pod 'HJTask', :path => '../../HJTask'
  
  #  pod 'HJNetwork'
  #  pod 'HJNetwork/Default'
  #  pod 'HJNetwork/DNS'
  #  pod 'HJNetwork/Upload'
  #  pod 'HJNetwork/Download'
  #  pod 'HJTask'
  
  pod 'HJCache'
  pod 'HJCache/SDBridge'
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImageFLIFCoder'
  pod 'SDWebImageSVGKitPlugin'
  
  pod 'WCDB'
  
  target 'HJNetworkDemoTests' do
    inherit! :search_paths
    #  pod 'HJNetwork', :path => '../'
    #  pod 'HJNetwork'
    #  pod 'HJCache'
  end
  
  target 'HJNetworkDemoUITests' do
    # Pods for testing
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
