# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ObjectiveC-Lib/Specs.git'     #私有仓库地址

platform :ios, '9.0'

target 'HJNetworkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HJNetworkDemo
  
  pod 'HJNetwork', :path => '../'
  pod 'HJTask', :path => '../../HJTask'
  pod 'HJCache/Default', :path => '../../HJCache'
  
#  pod 'HJNetwork'
#  pod 'HJTask'
#  pod 'HJCache/Default'
  
  pod 'SDWebImage'
  
end
